# Generated by Django 4.2.7 on 2023-12-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_image', models.ImageField(default='null.jpg', upload_to='blogimage')),
                ('b_name', models.CharField(max_length=20)),
                ('b_date', models.DateField()),
            ],
        ),
    ]
