# Generated by Django 4.2.7 on 2024-01-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_img',
            field=models.ImageField(default='null.jpg', upload_to='catimg'),
        ),
    ]
