# Generated by Django 4.2.7 on 2024-01-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
