# Generated by Django 4.2.7 on 2024-01-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='totalsize',
            field=models.IntegerField(default=0),
        ),
    ]
