# Generated by Django 4.2.7 on 2024-01-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_cart_totalsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datee', models.DateField()),
                ('addcomplain', models.CharField(max_length=30)),
            ],
        ),
    ]
