# Generated by Django 5.0.1 on 2024-01-16 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
