# Generated by Django 5.0.1 on 2024-01-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_image', models.ImageField(default='null.jpg', upload_to='blogimage')),
                ('b_name', models.CharField(max_length=20)),
                ('b_date', models.DateField()),
                ('b_enterblog', models.CharField(max_length=30)),
            ],
        ),
    ]
