# Generated by Django 4.2.7 on 2024-01-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='b_image',
            field=models.ImageField(upload_to='blogimage'),
        ),
    ]
