# Generated by Django 4.2.7 on 2024-01-25 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_blog_b_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
