# Generated by Django 4.2.7 on 2024-01-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_country', models.CharField(max_length=30)),
                ('od_address', models.CharField(max_length=30)),
                ('od_town', models.CharField(max_length=30)),
                ('od_pin', models.IntegerField()),
            ],
        ),
    ]
