# Generated by Django 4.2.7 on 2024-01-29 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='odproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='oduser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.register'),
        ),
    ]
